In [260]:
from tensorflow.keras.models import Sequential
from tensorflow.keras import layers
from tensorflow.keras.losses import MSE, MAE
from tensorflow.keras.activations import elu
from tensorflow.keras.optimizers import Adam, RMSprop
import numpy as np
import pandas as pd
import datetime

In [261]:
train_x = np.load('/home/toliman/Desktop/train_x.npy')
train_y = np.load('/home/toliman/Desktop/train_y.npy')
targets = np.load('/home/toliman/Desktop/targets.npy')

In [265]:
train_x

array([[5.00614504e-04, 0.00000000e+00, 2.50307252e-03, ...,
        1.00000000e+00, 2.42547727e-03, 2.50307252e-05],
       [5.00614504e-04, 0.00000000e+00, 2.50307252e-03, ...,
        1.00000000e+00, 2.42547727e-03, 2.50307252e-05],
       [5.00614504e-04, 0.00000000e+00, 2.50307252e-03, ...,
        1.00000000e+00, 2.42547727e-03, 2.50307252e-05],
       ...,
       [1.62940755e-03, 0.00000000e+00, 2.44411132e-03, ...,
        1.00000000e+00, 7.89447957e-03, 8.14703774e-05],
       [1.62940755e-03, 0.00000000e+00, 2.44411132e-03, ...,
        1.00000000e+00, 7.89447957e-03, 8.14703774e-05],
       [1.62940755e-03, 0.00000000e+00, 2.44411132e-03, ...,
        1.00000000e+00, 7.89447957e-03, 8.14703774e-05]])

In [ ]:
from sklearn.model_selection import train_test_split

x_train, x_val, y_train, y_val = train_test_split(train_x, train_y, shuffle=False)

In [ ]:
network = Sequential(
    [
        layers.Dense(64, input_shape=(train_x.shape[1],), activation='relu'),
        layers.Dense(96, activation='relu'),
        layers.Dense(128, activation='relu'),
        layers.Dense(128, activation='relu'),
        layers.Dense(64, activation='relu'),
        layers.Dense(32, activation='relu'),
        layers.Dense(16, activation='relu'),
        layers.Dense(1, activation='sigmoid'),
    ]
)

network.summary()

In [211]:
from tensorflow.keras.metrics import RootMeanSquaredError

network.compile(
    optimizer=RMSprop(learning_rate=.00025),
    loss=MAE,
    metrics=[RootMeanSquaredError(), ],
)

In [212]:
network.fit(
    x_train,
    y_train,
    batch_size=128,
    epochs=30,
    validation_data=(x_val, y_val,),
)

network.save('billyboard.v4.h5')

In [229]:
x = np.random.choice(train_x.shape[0], 100, replace=False)

[349795 253029 112955 108423 224600  86995 423299 109119 147683 173496
 187887   9343 194283  20197 382489 391888  66360  68550 489220 132546
  83820  71058 491387  99442 291193 422894 485736 341267 456496  27314
  71392 459739 429273 224606 476291 338507  55158 197054 194459  35023
 484883  61474 100778 212618 376866 171441 262929 270567 350401  42420
 452781 386460 355716 251974  45767 237757  16995 465413 151510 154770
 440688 346089 297889 207564 175458 395055 336879 101973 422317 230391
 124257 478372 365413 310627   2504 304970 360332 162628 456752 189483
 192969 324301 309918  73370  67636 315480 461972  53516  94870 271119
 237473 132765 491170  38607  61414 154737 292968  35977 259437 307459]


[array([0.01867449], dtype=float32),
 array([-0.523291], dtype=float32),
 array([-0.47723606], dtype=float32),
 array([-0.20820607], dtype=float32),
 array([-0.45991397], dtype=float32),
 array([-0.40131956], dtype=float32),
 array([-0.41170713], dtype=float32),
 array([-0.23011386], dtype=float32),
 array([-0.24742055], dtype=float32),
 array([-0.3967101], dtype=float32),
 array([-0.18114886], dtype=float32),
 array([-0.32363036], dtype=float32),
 array([-0.44319892], dtype=float32),
 array([-0.35930017], dtype=float32),
 array([-0.22344264], dtype=float32),
 array([-0.26143992], dtype=float32),
 array([-0.39245582], dtype=float32),
 array([-0.15782848], dtype=float32),
 array([-0.41229364], dtype=float32),
 array([-0.44706666], dtype=float32),
 array([-0.37973174], dtype=float32),
 array([-0.45624548], dtype=float32),
 array([-0.34998807], dtype=float32),
 array([-0.48426077], dtype=float32),
 array([-0.3599795], dtype=float32),
 array([-0.24499516], dtype=float32),
 array([-0.308639

In [ ]:
pred = network.predict(train_x[x])

ar = train_y[x]

print(list(zip(pred, ar)))